---
kind: pipeline
name: tests

steps:
- name: run-tests
  image: node:10.16.0
  commands:
    - chmod +x ./bin/run.sh
    - ./bin/run.sh
  when:
    event:
    - pull_request
    - push

trigger:
  branch:
  - master
  event:
  - push
  - pull_request

---
kind: pipeline
name: npm

steps:
- name: publish-email-service
  image: plugins/npm
  settings:
    username:
      from_secret: npm_username
    password:
      from_secret: npm_password
    email:
      from_secret: npm_email

trigger:
  event:
  - tag
