pipeline:
  run-mongo-tests:
    image: node:10.13.0
    commands:
      - chmod +x ./bin/run.sh
      - ./bin/run.sh
    when:
      status: [ failure, success ]
      event: [pull_request]

  publish-node-mongo:
    image: plugins/npm
    secrets: [ npm_username, npm_email, npm_password ]
    when:
      event: [ tag ]
      branches: [ master ]

branches: [ master, "*:master" ]
